// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "description": "Authenticate a user with username and password, returns session token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request (validation failed)",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_presentation_v1_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_presentation_v1_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_presentation_v1_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/record/telegram/identity": {
            "post": {
                "description": "Add new telegram identity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "record"
                ],
                "summary": "Add new telegram identity",
                "parameters": [
                    {
                        "description": "Identity creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AddTelegramIdentityRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Identity created successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.AddTelegramIdentityResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Insufficient privileges",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "You have already added this identity",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/users/": {
            "post": {
                "description": "Create a new user with username, display name, password and role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createUserForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/{id}": {
            "get": {
                "description": "Retrieve a user's information by their ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User found",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently remove a user from the system",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/{id}/demote": {
            "patch": {
                "description": "Change a user's role from admin to user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Demote user to regular user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User demoted successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/{id}/promote": {
            "patch": {
                "description": "Change a user's role from user to admin",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Promote user to admin",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User promoted successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/internal_user_presentation_v1_handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AddTelegramIdentityRequest": {
            "type": "object",
            "properties": {
                "telegram_bio": {
                    "type": "string",
                    "example": "Hi! I am using Whatsapp"
                },
                "telegram_first_name": {
                    "type": "string",
                    "example": "John"
                },
                "telegram_id": {
                    "type": "string",
                    "example": "20d8a06c-2fac-4643-ba78-7da267a7fe51"
                },
                "telegram_last_name": {
                    "type": "string",
                    "example": "Doe"
                },
                "telegram_phone_number": {
                    "type": "string",
                    "example": "+11234567890 (Use e164 format)"
                },
                "telegram_username": {
                    "type": "string",
                    "example": "user1235"
                }
            }
        },
        "handlers.AddTelegramIdentityResponse": {
            "type": "object",
            "properties": {
                "record_id": {
                    "type": "string",
                    "example": "28736582143"
                }
            }
        },
        "handlers.CreateUserResponse": {
            "description": "User creation response with ID",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "019b1a49-dbf6-74d6-97bf-2d7e57d30c75"
                },
                "message": {
                    "type": "string",
                    "example": "The user has been created. You can login now"
                }
            }
        },
        "handlers.GetUserResponse": {
            "description": "User information response",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-12-14T00:36:46.545Z"
                },
                "display_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "id": {
                    "type": "string",
                    "example": "019b1a49-dbf6-74d6-97bf-2d7e57d30c75"
                },
                "user_role": {
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ],
                    "example": "user"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "handlers.LoginResponse": {
            "description": "Login response with session token",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Login successful"
                },
                "token": {
                    "type": "string",
                    "example": "dGVzdC10b2tlbi0xMjM0NTY3ODkw"
                }
            }
        },
        "handlers.SuccessResponse": {
            "description": "Standard success response with message",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "User promoted to admin successfully"
                }
            }
        },
        "handlers.createUserForm": {
            "type": "object",
            "required": [
                "display_name",
                "password",
                "user_role",
                "username"
            ],
            "properties": {
                "display_name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "user_role": {
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ]
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 2
                }
            }
        },
        "handlers.loginForm": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 2
                }
            }
        },
        "internal_auth_presentation_v1_handlers.ErrorResponse": {
            "description": "Standard error response",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid credentials"
                }
            }
        },
        "internal_user_presentation_v1_handlers.ErrorResponse": {
            "description": "Standard error response",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request body"
                }
            }
        }
    },
    "securityDefinitions": {
        "SessionCookie": {
            "description": "Session cookie for authenticated requests. Roles: Admin, User",
            "type": "apiKey",
            "name": "session_id",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Trinity API",
	Description:      "Trinity API schema.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
